### ISSUE TITLE
Which tags

### ISSUE THREAD

**Issue by gedw99** [agent306/nfc_io#1]
I wonder if I can talk to FIDO2 hardware devices like yubikeys ?

**Comment by agent306** [comment]
> I wonder if I can talk to FIDO2 hardware devices like yubikeys ?

As far as my knowledge goes, I don't think Android or iOS capabilities are quite there yet. I might be wrong thought. Would really appreciate it if you could enlighten me.

**Comment by agent306** [comment]
> I wonder if I can talk to FIDO2 hardware devices like yubikeys ?

As far as my knowledge goes, I don't think Android or iOS capabilities are quite there yet. I might be wrong though. Would really appreciate it if you could enlighten me.

This is what I found on the topic so far:
[https://fidoalliance.org/android-now-fido2-certified-accelerating-global-migration-beyond-passwords/](https://fidoalliance.org/android-now-fido2-certified-accelerating-global-migration-beyond-passwords/)

As far as this article goes, it only explains that Android phones can act as FIDO2 certified keys

**Comment by agent306** [comment]
> Which tags

I'll update the tags in the readme
